Class {
	#name : 'GbxActivation',
	#superclass : 'Object',
	#instVars : [
		'session',
		'gsMethod',
		'gsMethodId',
		'receiver',
		'remoteSelf',
		'selector',
		'quickStepPoint',
		'sourceOffsets',
		'argAndTempNames',
		'sourceString',
		'ipOffset',
		'process',
		'level',
		'receiverClass',
		'mclass',
		'deferredInfo',
		'stackP',
		'numArgsAndTemps',
		'serverCallContext',
		'convertedTempNames'
	],
	#category : 'GemStone-GBS-Converted',
	#package : 'GemStone-GBS-Converted'
}
