Class {
	#name : 'GbxBrowser',
	#superclass : 'Model',
	#instVars : [
		'session',
		'userProfile',
		'methodTabSetting',
		'textMode',
		'dictionaryList',
		'classList',
		'protocolList',
		'methodList',
		'textValue',
		'stepPoint',
		'tabs',
		'metaClass',
		'left',
		'right',
		'methodSymbols',
		'classIsModifiable',
		'sourceText',
		'breakPointList'
	],
	#category : 'GemStone-GBS-Converted',
	#package : 'GemStone-GBS-Converted'
}
