Class {
	#name : 'GbxCollectionCache',
	#superclass : 'Object',
	#instVars : [
		'elements',
		'delegate',
		'actualSize',
		'initialBufferSize',
		'cachedRanges',
		'valueOops',
		'valueNames',
		'classOops',
		'classNames',
		'isClass',
		'keyOops',
		'keyNames',
		'keyClassOops',
		'keyClassNames',
		'keyIsClass'
	],
	#category : 'GemStone-GBS-Converted',
	#package : 'GemStone-GBS-Converted'
}
