Class {
	#name : 'GbxServerInterface',
	#superclass : 'Object',
	#instVars : [
		'alteredOopBuffer',
		'byteFetchBuffer',
		'callSequencer',
		'clampedTravArgsBuffer',
		'dirtyOopBuffer',
		'eventDetector',
		'gcedOopBuffer',
		'longHolderBuffer',
		'longHolderBuffer2',
		'needMoreTraversal',
		'oopFetchBuffer',
		'oopsNoLongerReplicatedBuffer',
		'singleStepIsRequested',
		'storeTravDoArgsBuffer',
		'noLongerReplicatedOops',
		'thisSession',
		'traversalBufferManager'
	],
	#category : 'GemStone-GBS-Converted',
	#package : 'GemStone-GBS-Converted'
}
