Class {
	#name : 'GbxServerInteraction',
	#superclass : 'Object',
	#instVars : [
		'argumentDelegates',
		'arguments',
		'fetchTraversal',
		'interactionState',
		'replicationClampDelegate',
		'replication',
		'replicationLevel',
		'replicationScheme',
		'resultDelegateOrError',
		'serverInterface',
		'session',
		'shouldReplicateResultBodyAsDelegates',
		'shouldReplicateResult',
		'shouldSynchronize',
		'statResource',
		'stopForBreakpoints',
		'storeTraversal'
	],
	#category : 'GemStone-GBS-Converted',
	#package : 'GemStone-GBS-Converted'
}
